### PR TITLE
feat(servers): add catgir.ls

### PR DESCRIPTION
**Pull request by e991f665b7e62df5a54fdef19053a4e75117b89**
Added the catgir.ls Matrix server

### CODE REVIEW

**Comment by austinhuang0131** [comment]
1. alphabetic order please
2. since when was your server established?
3. i assume you know you need to at least promise me you're going to maintain its stability for the long term

**Comment by e991f665b7e62df5a54fdef19053a4e75117b89** [comment]
Hi - apologies, didn't see that text

Matrix server has been running for ~1 day, however, the infrastructure which I run everything relating to catgir.ls on has been up for around 7 months, and yes, I do intend on keeping the Matrix server maintained, there's around 20-30 active users currently

**Comment by austinhuang0131** [comment]
as per convention i'll apply a timeout of 1 week

also, at least for Element, it was not advised to run your client and your server on the same (sub)domain (i forgot where they said that but they consider it a XSS risk), you might want to consider this

**Comment by e991f665b7e62df5a54fdef19053a4e75117b89** [comment]
Sounds good, I'll change around my nginx config to serve the web-client on the `cinny` subdomain

**Comment by e991f665b7e62df5a54fdef19053a4e75117b89** [comment]
Bumping this as the catgir.ls Matrix has been operating for 7 days now.

**Pull request merged**
