### PR TITLE
Commitment of all

### PR DESCRIPTION
**Pull request by HPOA909**
Please look the files below

### CODE REVIEW

**Comment by austinhuang0131** [comment]
no like did you actually set up delegation?

**Comment by HPOA909** [comment]
I re-edit everything as suppose to be

**Comment by austinhuang0131** [comment]
yes but your server doesn't have domain delegation: https://federationtester.matrix.org/#2b9t.xyz

**Comment by HPOA909** [comment]
I am currently fixing it for the next few weeks

**Comment by austinhuang0131** [comment]
then how should i believe in your server's stability for the long term?

**Comment by HPOA909** [comment]
There's will be weekly update in every Friday about all situations of all services in the [forum](https://forum.2b9t.xyz).

**Comment by HPOA909** [comment]
@austinhuang0131 : have you encountered this [report](https://federationtester.matrix.org/#2b9t.xyz) before? How could I fix these errors?

**Comment by austinhuang0131** [comment]
first, your certificate is not valid for `matrix.2b9t.xyz`

second, every endpoint on `matrix.2b9t.xyz` and `2b9t.xyz` returns `{"m.server": "matrix.2b9t.xyz:443"}`

since i strongly doubt the stability of your homeserver i'm gonna time this out for 2 months

**Comment by HPOA909** [comment]
alrighty, I will come back for about 3 months or so.

**Pull request closed without merging**
